# Generated by Django 5.2.3 on 2025-06-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_text', models.CharField(help_text='541cd55155165', max_length=100, unique=True)),
                ('spawn', models.CharField(help_text='spawn in plains biome on top of a woodland mansion', max_length=500)),
                ('cherry_grove_distance', models.IntegerField(blank=True, null=True)),
                ('cherry_grove_coords', models.CharField(blank=True, max_length=50, null=True)),
                ('pale_garden_distance', models.IntegerField(blank=True, null=True)),
                ('pale_garden_coords', models.CharField(blank=True, max_length=50, null=True)),
                ('mangrove_swamp_distance', models.IntegerField(blank=True, null=True)),
                ('mangrove_swamp_coords', models.CharField(blank=True, max_length=50, null=True)),
                ('mansion_distance', models.IntegerField(blank=True, null=True)),
                ('mansion_coords', models.CharField(blank=True, max_length=50, null=True)),
                ('monument_distance', models.IntegerField(blank=True, null=True)),
                ('monument_coords', models.CharField(blank=True, max_length=50, null=True)),
                ('ancient_city_distance', models.IntegerField(blank=True, null=True)),
                ('ancient_city_coords', models.CharField(blank=True, max_length=50, null=True)),
                ('desert_temple_distance', models.IntegerField(blank=True, null=True)),
                ('desert_temple_coords', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
